### PR TITLE
Refactor map widget

### PR DESCRIPTION
**Pull request by tarleb**
Various small changes to `widget/Map.php` and a minor addition to the `README`.

This PR contains commits also present in #13.  The idea is to reduce the size of  that monster-PR, making it easier to discuss changes in their respective context.

### CODE REVIEW

**Comment by tonydspaniard** [comment]
Thank you so much @tarleb... I am quite busy atm, I will come back to your PRs as soon as possible. Apologies.

**Comment by tarleb** [comment]
no hurries

**Comment by tonydspaniard** [comment]
All good

**Comment by tonydspaniard** [comment]
Thanks!

**Pull request merged**
